platform :ios, '8.0'
use_frameworks!

target ‘BKDouyuTV’ do



pod 'SVProgressHUD', '~> 2.0.3'
   pod 'MJExtension', '~> 3.0.13'
pod 'Alamofire', '~> 3.0'
pod 'SnapKit' , ‘~>  0.22.0’


end

target ‘BKDouyuTVTests’ do
pod 'SVProgressHUD', '~> 2.0.3'
   pod 'MJExtension', '~> 3.0.13'
pod 'Alamofire', '~> 3.0'
pod 'SnapKit' , ‘~>  0.22.0’



end

post_install do |installer| 
 installer.pods_project.targets.each do |target|
 target.build_configurations.each do |config|
 config.build_settings['SWIFT_VERSION'] = ‘2.3’
 end
 end
end